In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
ciudades ={
    11001: 'Bogotá', 76001: 'Cali', 5001: 'Medellín', 66001: 'Pereira', 13001: 'Cartagena', 
    50001: 'Villavicencio', 8001: 'Barranquilla', 68001: 'Bucaramanga', 23001: 'Monteria', 
    73001: 'Ibague', 54001: 'Cucuta', 17001: 'Manizales', 52001: 'Pasto'
}
preguntas = {'P220':'Sexo','P5785':'Edad','P1365':'Ocupacion' }
url_personas ='https://raw.githubusercontent.com/AndresER23/PROJECT_ML/refs/heads/master/Caracteristicas%20generales%20de%20las%20personas.CSV'
df_personas = pd.read_csv(url_personas, sep=';')
df_personas= df_personas.drop(['FEX_C','ORDEN','SECUENCIA_ENCUESTA','SECUENCIA_P','NRO_ENCUESTA','P5501','P2057','P2059','P2061','P1402','P1403','P1364','P1363'], axis=1)
df_personas = df_personas.rename(columns=preguntas)
df_personas['Ocupacion'].value_counts()
ocupacion_map = {
    1: 'Trabajando',
    2: 'Buscando trabajo',
    3: 'Estudiando',
    4: 'Oficios del hogar',
    5: 'Incapacitado permanente para trabajar',
    6: 'Pensionado',
    7: 'Ocio',
    8: 'Otra actividad'
}
sexo_map = {
    1: 'Hombre',
    2: 'Mujer'}
# Reemplazar los valores en la columna 'Ocupacion'
df_personas['Ocupacion'] = df_personas['Ocupacion'].replace(ocupacion_map)
df_personas['Sexo'] = df_personas['Sexo'].replace(sexo_map)
df_personas

        DIRECTORIO    Sexo  Edad         Ocupacion
0           600000   Mujer    21  Buscando trabajo
1           600000   Mujer     3               NaN
2           600000   Mujer    77        Trabajando
3           600001  Hombre    38        Trabajando
4           600002   Mujer    52        Trabajando
...            ...     ...   ...               ...
122246      646827  Hombre    50        Trabajando
122247      646827  Hombre    12               NaN
122248      646828  Hombre    43        Trabajando
122249      646828   Mujer    40        Trabajando
122250      646828  Hombre     8               NaN

[122251 rows x 4 columns]

In [5]:
url_viviendas = 'https://raw.githubusercontent.com/AndresER23/PROJECT_ML/refs/heads/master/Datos%20de%20la%20vivienda.CSV'
df_viviendas= pd.read_csv(url_viviendas, sep=';')
df_viviendas = df_viviendas.drop(['FEX_C','ORDEN','SECUENCIA_ENCUESTA','SECUENCIA_P','NRO_ENCUESTA','P1987','P1988','P1989','P1990'], axis=1)
df_viviendas['DEPMUNI'] = df_viviendas['DEPMUNI'].replace(ciudades)
df_viviendas = df_viviendas.rename(columns={'DEPMUNI':'Ciudad','P1988S1':'Estrato'})
df_viviendas = df_viviendas.drop(['CIUDADES28'], axis=1)
df_viviendas

       DIRECTORIO     Ciudad     Clase  Estrato
0          600000          0  Cabecera      1.0
1          600001          0  Cabecera      1.0
2          600002          0  Cabecera      1.0
3          600003          0  Cabecera      1.0
4          600004          0  Cabecera      1.0
...           ...        ...       ...      ...
41281      646818  Manizales  Cabecera      2.0
41282      646819  Manizales  Cabecera      3.0
41283      646820  Manizales  Cabecera      3.0
41284      646827  Manizales  Cabecera      2.0
41285      646828  Manizales  Cabecera      6.0

[41286 rows x 4 columns]

In [6]:
df_percepcion = pd.read_csv('Percepcion de seguridad y convivencia.CSV', sep=';')
df_percepcion = df_percepcion.drop(['FEX_C','ORDEN','SECUENCIA_ENCUESTA','SECUENCIA_P','NRO_ENCUESTA'], axis=1)
preguntas_percepcion = {'P3001':'Seguridad', 'P1361S1':'Agresiones', 'P1361S15':'Agresiones fisicas','P1361S14':'Agresiones Sexuales','P1361S2':'Información medios de comunicación',
     'P1361S16' :'Informacion redes sociales o calles','P1361S3':'Poca presencia fuerza publica','P1361S4':'Delincuencia Comun','P1361S5':'Presencia pandillas','P1361S6':'Poca iluminación',
      'P1361S7': 'Expendio consumo drogas','P1361S9': 'm. Porque hay presencia de guerrilla.',
    'P1361S10': 'n. Porque hay presencia de grupos armados organizados.',
    'P1361S12': 'o. Porque existen cultivos ilícitos cercanos.',
    'P1361S13': 'p. Porque hay minería ilegal.'              
}
df_percepcion['DIRECTORIO'].is_unique

False

In [7]:
df_unido = pd.merge(df_personas, df_viviendas, on='DIRECTORIO')

# Filtrar solo las ciudades de Medellín, Cali y Bogotá
df_unido = df_unido[df_unido['Ciudad'].isin(['Medellín', 'Cali', 'Bogotá'])]
df_unido

,DIRECTORIO,Sexo,Edad,Ocupacion,Ciudad,Clase,Estrato
4272,601351,Hombre,45,Trabajando,Bogotá,Cabecera,2.0
4273,601351,Hombre,84,Incapacitado permanente para trabajar,Bogotá,Cabecera,2.0
4274,601352,Mujer,60,Trabajando,Bogotá,Cabecera,1.0
4275,601352,Hombre,81,Incapacitado permanente para trabajar,Bogotá,Cabecera,1.0
4276,601353,Hombre,58,Trabajando,Bogotá,Cabecera,3.0
...,...,...,...,...,...,...,...
122202,646791,Mujer,34,Trabajando,Bogotá,Cabecera,3.0
122203,646792,Mujer,34,Trabajando,Bogotá,Cabecera,3.0
122204,646792,Hombre,40,Trabajando,Bogotá,Cabecera,3.0
122205,646792,Hombre,15,Estudiando,Bogotá,Cabecera,3.0
122206,646793,Mujer,42,Trabajando,Bogotá,Cabecera,3.0

In [8]:
df_unido['Ciudad'].value_counts()

Ciudad
Bogotá      6328
Medellín    6151
Cali        5896
Name: count, dtype: int64

In [9]:
# Verificar si hay valores nulos en el DataFrame filtrado
valores_nulos = df_unido.isnull().sum()

# Mostrar el número de valores nulos por columna
print(valores_nulos)

# Verificar si hay alguna fila con valores nulos
filas_con_nulos = df_unido[df_unido.isnull().any(axis=1)]

# Mostrar las filas que tienen valores nulos
print(filas_con_nulos)

DIRECTORIO       0
Sexo             0
Edad             0
Ocupacion     3272
Ciudad           0
Clase            0
Estrato         67
dtype: int64
        DIRECTORIO    Sexo  Edad Ocupacion  Ciudad     Clase  Estrato
5066        601629   Mujer     5       NaN    Cali  Cabecera      2.0
5069        601630   Mujer    11       NaN    Cali  Cabecera      2.0
5072        601630  Hombre     3       NaN    Cali  Cabecera      2.0
5075        601631   Mujer    10       NaN    Cali  Cabecera      2.0
5077        601632  Hombre     4       NaN    Cali  Cabecera      2.0
...            ...     ...   ...       ...     ...       ...      ...
122072      646702   Mujer    14       NaN  Bogotá  Cabecera      2.0
122073      646702  Hombre    12       NaN  Bogotá  Cabecera      2.0
122075      646704   Mujer     9       NaN    Cali  Cabecera      1.0
122079      646709   Mujer     8       NaN    Cali  Cabecera      1.0
122082      646710  Hombre    11       NaN    Cali  Cabecera      1.0

[3333 rows x 7 columns]

In [10]:
filas_con_nulos

        DIRECTORIO    Sexo  Edad Ocupacion  Ciudad     Clase  Estrato
5066        601629   Mujer     5       NaN    Cali  Cabecera      2.0
5069        601630   Mujer    11       NaN    Cali  Cabecera      2.0
5072        601630  Hombre     3       NaN    Cali  Cabecera      2.0
5075        601631   Mujer    10       NaN    Cali  Cabecera      2.0
5077        601632  Hombre     4       NaN    Cali  Cabecera      2.0
...            ...     ...   ...       ...     ...       ...      ...
122072      646702   Mujer    14       NaN  Bogotá  Cabecera      2.0
122073      646702  Hombre    12       NaN  Bogotá  Cabecera      2.0
122075      646704   Mujer     9       NaN    Cali  Cabecera      1.0
122079      646709   Mujer     8       NaN    Cali  Cabecera      1.0
122082      646710  Hombre    11       NaN    Cali  Cabecera      1.0

[3333 rows x 7 columns]

In [11]:
url_aporte = 'https://raw.githubusercontent.com/AndresER23/PROJECT_ML/refs/heads/master/Percepcion%20del%20aporte%20a%20la%20seguridad.CSV'
df_aporte = pd.read_csv(url_aporte, sep=';')
df_aporte = df_aporte.drop(['FEX_C','ORDEN','SECUENCIA_ENCUESTA','SECUENCIA_P','NRO_ENCUESTA'], axis=1)
preguntas_aporte ={ 'P1182S1':'Aporte_policia',
                   'P1182S2':'Aporte_fuerzas_armadas',
                    'P1182S3':'Aporte_alcaldia',
                    'P1181S1': 'Aporte_justicia_fiscalia', #Con relación al desempeño en la administración de justicia, ¿cuánto considera que contribuyen a la seguridad ciudadana las siguientes instituciones de la rama judicial
                    'P1181S2':'Aporte_justicia_jueces',
                    'P3317S1': 'Aported_convivencia_ICBF', #¿Cuánto cree... que contribuyen las siguientes instituciones a la convivencia de la ciudad o municipio de
                    'P3317S2':'Aporte_convivencia_InspeccionesPolicia',
                    'P3317S3':'Aporte_convivencia_CentroConciliacion',
                    'P3321': 'Nivel_satisfaccion_policia',
                    'P3119':'Nivel_confianza_policia'
}

In [12]:
columnas_conservar = ['DIRECTORIO'] + list(preguntas_aporte.keys())
df_aporte_filtrado = df_aporte[columnas_conservar]
renombrar_columnas = {'DIRECTORIO': 'DIRECTORIO'}
renombrar_columnas.update(preguntas_aporte)
df_aporte_filtrado = df_aporte_filtrado.rename(columns=renombrar_columnas)

In [13]:
df_aporte_filtrado

,DIRECTORIO,Aporte_policia,Aporte_fuerzas_armadas,Aporte_alcaldia,Aporte_justicia_fiscalia,Aporte_justicia_jueces,Aported_convivencia_ICBF,Aporte_convivencia_InspeccionesPolicia,Aporte_convivencia_CentroConciliacion,Nivel_satisfaccion_policia,Nivel_confianza_policia
0,600000,2,3,2,2,2,2,2,2,3,3
1,600000,1,3,2,2,2,1,1,2,4,4
2,600001,1,2,2,2,2,2,1,2,3,4
3,600002,2,2,2,2,2,2,2,2,3,3
4,600002,2,2,2,2,2,2,2,2,3,3
...,...,...,...,...,...,...,...,...,...,...,...
95383,646820,1,1,3,3,3,1,3,3,4,4
95384,646827,3,3,3,3,3,3,3,3,3,3
95385,646827,2,2,3,3,3,2,3,3,3,3
95386,646828,1,2,2,2,2,2,2,2,3,3
95387,646828,1,2,2,2,2,2,2,2,3,3

In [14]:
valores_nulos = df_aporte_filtrado.isnull().sum()
# Mostrar el número de valores nulos por columna
print(valores_nulos)

DIRECTORIO                                0
Aporte_policia                            0
Aporte_fuerzas_armadas                    0
Aporte_alcaldia                           0
Aporte_justicia_fiscalia                  0
Aporte_justicia_jueces                    0
Aported_convivencia_ICBF                  0
Aporte_convivencia_InspeccionesPolicia    0
Aporte_convivencia_CentroConciliacion     0
Nivel_satisfaccion_policia                0
Nivel_confianza_policia                   0
dtype: int64

In [ ]:
url_delitos = 'https://raw.githubusercontent.com/AndresER23/PROJECT_ML/refs/heads/master/Filtro%20de%20delitos.CSV'
df_delitos = pd.read_csv(url_delitos, sep=';')
df_delitos = df_delitos.drop(['FEX_C','ORDEN','SECUENCIA_ENCUESTA','SECUENCIA_P','NRO_ENCUESTA'], axis=1)
preguntas_delitos ={ 'P541': 'Victima_hurto_residencial_2022',
                    'P1392': 'Victima_hurto_residencial_2021',
                    'P1392S1': 'Cuantas_veces_hurto_residencial_2021',
                    'P1392S3': 'Denuncia_Cuantas_veces_hurto_residencial_2021',
                    'P525': 'Hurto_objeto_personal_2022',
                    'P1343': 'Hurto_objeto_personal_2021',
                    'P523': 'Victima_hurto_vehiculo_2022',
                    'P1179':'Hurto_vehiculo_2021',
                    'P1179S1':'Cuantas_veces_hurto_vehiculo_2021',
                    'P1179S3':'Denuncia_Cuantas_veces_hurto_vehiculo_2021',
                    'P1343S1': 'Cuantas_veces_hurto_objeto_personal_2021',
                    'P1343S3': 'Denuncia_Cuantas_veces_hurto_objeto_personal_2021',
                    'P3304':'Victima_delito_cibernetico_2022', # ¿... experimentó algún incidente relacionado con el uso de medios digitales o cibernéticos, por ejemplo, hackeo de sus cuentas de correo o redes sociales, ciberacoso, software malicioso, etc.?
                    'P3306':'Victima_delito_cibernetico_2021',
                    'P3306S1':'Cuantas_veces_delito_cibernetico_2021',
                    'P3306S2':'Denuncia_Cuantas_veces_delito_cibernetico_2021',
                    'P526': 'Implicado_violencia_fisica_2022', #¿... se ha visto involucrado(a) en riñas o peleas que impliquen violencia física?
                    'P1315': 'Implicado_violencia_fisica_2021',
                    'P1315S1': 'Cuantas_veces_violencia_fisica_2021',
                    'P1315S3': 'Denuncia_Cuantas_veces_violencia_fisica_2021',
                    'P528':'Victima_extorsion_2022',
                    'P1286':'Victima_extorsion_2021',
                    'P1976S1':'Victima_fraude_2022',
                    'P1976S2':'Victima_amenazas_2022',
                    'P1976S9':'Victima_acoso_laboral_2022',
                    'P1976S4':'Victima_acoso_escolar_2022',
                    'P1976S5':'Victima_secuestro_2022',
                    'P1976S6':'Victima_invasiones_domiciliarias_2022',
                    'P1976S7':'Victima_desplazamiento_2022',
                    'P1976S13':'Victima_acoso_callejero_2022',
                    'P1976S14':'Victima_acoso_sexual_2022'


            } 
columnas_conservar = ['DIRECTORIO'] + list(preguntas_delitos.keys())
df_delitos_filtrado = df_delitos[columnas_conservar]
renombrar_columnas = {'DIRECTORIO': 'DIRECTORIO'}
renombrar_columnas.update(preguntas_delitos)
df_delitos_filtrado = df_delitos_filtrado.rename(columns=renombrar_columnas)
df_delitos_filtrado

,DIRECTORIO,Victima_hurto_residencial_2022,Victima_hurto_residencial_2021,Cuantas_veces_hurto_residencial_2021,Denuncia_Cuantas_veces_hurto_residencial_2021,Hurto_objeto_personal_2022,Hurto_objeto_personal_2021,Victima_hurto_vehiculo_2022,Hurto_vehiculo_2021,Cuantas_veces_hurto_vehiculo_2021,...,Victima_extorsion_2021,Victima_fraude_2022,Victima_amenazas_2022,Victima_acoso_laboral_2022,Victima_acoso_escolar_2022,Victima_secuestro_2022,Victima_invasiones_domiciliarias_2022,Victima_desplazamiento_2022,Victima_acoso_callejero_2022,Victima_acoso_sexual_2022
0,600000,2.0,2.0,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
1,600000,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
2,600001,2.0,2.0,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
3,600002,2.0,2.0,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
4,600002,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95383,646820,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
95384,646827,2.0,2.0,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
95385,646827,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,...,2,2,2,2,2,2,2,2,2,2
95386,646828,2.0,2.0,NaN,NaN,2,2,2.0,2.0,NaN,...,2,2,2,2,2,2,2,2,2,2
95387,646828,NaN,NaN,NaN,NaN,2,2,2.0,2.0,NaN,...,2,2,2,2,2,2,2,2,2,2